//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  ColliderBit sources for model @MODEL@.
///
///  Automatically generated by GUM.
///
///  \author The GAMBIT Collaboration
///          http://gambit.hepforge.org
///  \date @DATETIME@
///
///  *********************************************

#include "gambit/ColliderBit/getPy8Collider.hpp"
#include "gambit/ColliderBit/generateEventPy8Collider.hpp"
#include "gambit/ColliderBit/getBuckFast.hpp"
#include "gambit/ColliderBit/smearEvent.hpp"


namespace Gambit
{
  namespace ColliderBit
  {

    // Get Monte Carlo event generator
    GET_SPECIFIC_PYTHIA(getPythia_@MODEL@, Pythia_@MODEL@_default, @MODEL@_spectrum, _@MODEL@, NOT_SUSY)
    GET_PYTHIA_AS_BASE_COLLIDER(getPythia_@MODEL@AsBase)

    // Run event generator
    GET_PYTHIA_EVENT(generateEventPythia_@MODEL@, Pythia_@MODEL@_default::Pythia8::Event)

    // Get detector simulations
    GET_BUCKFAST_AS_BASE_DETECTOR(getBuckFastATLASPythia_@MODEL@, Pythia_@MODEL@_default::Pythia8::Event, ATLAS)
    GET_BUCKFAST_AS_BASE_DETECTOR(getBuckFastCMSPythia_@MODEL@, Pythia_@MODEL@_default::Pythia8::Event, CMS)
    GET_BUCKFAST_AS_BASE_DETECTOR(getBuckFastIdentityPythia_@MODEL@, Pythia_@MODEL@_default::Pythia8::Event, Identity)

    // Run detector simulations
    SMEAR_EVENT(smearEventATLAS_@MODEL@, ATLAS)
    SMEAR_EVENT(smearEventCMS_@MODEL@, CMS)
    SMEAR_EVENT(copyEvent_@MODEL@, Identity)

  }
}
