//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend FlexibleSUSY_CMSSM 2.0.1.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#include "gambit/Backends/backend_types/FlexibleSUSY_CMSSM_2_0_1/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace FlexibleSUSY_CMSSM_2_0_1
        {
            namespace softsusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_0_1::softsusy::QedQcd QedQcd;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_0_1::flexiblesusy::Spectrum_generator_settings Spectrum_generator_settings;
            }
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)
BE_CONV_FUNCTION(run_FS_Spectrum, void, (Spectrum&, const SpectrumInputs&), "FS_CMSSM_Spectrum")


// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
