//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend FlexibleSUSY_CMSSM 2.4.0.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///  \date 06:02PM on October 23, 2019
///
///  *********************************************

#include "gambit/Backends/backend_types/FlexibleSUSY_CMSSM_2_4_0/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace FlexibleSUSY_CMSSM_2_4_0
        {
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::CMSSM_input_parameters CMSSM_input_parameters;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::CMSSM_scales CMSSM_scales;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::CMSSM_slha_io CMSSM_slha_io;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Physical_input Physical_input;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Spectrum_generator_problems Spectrum_generator_problems;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Error Error;
            }
            namespace softsusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::softsusy::QedQcd QedQcd;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::CMSSM_spectrum_generator_Two_scale CMSSM_spectrum_generator_Two_scale;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::CMSSM_slha_Model_Two_scale CMSSM_slha_Model_Two_scale;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Spectrum_generator_settings Spectrum_generator_settings;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::CMSSM_parameter_getter CMSSM_parameter_getter;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Command_line_options Command_line_options;
            }
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
