//
// Frontend header generated by BOSS for GAMBIT backend FlexibleSUSY_CMSSM 2.4.0.
//

#include "gambit/Backends/backend_types/FlexibleSUSY_CMSSM_2_4_0/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace FlexibleSUSY_CMSSM_2_4_0
        {
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Command_line_options Command_line_options;
            }
            namespace softsusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::softsusy::QedQcd QedQcd;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Spectrum_generator_problems Spectrum_generator_problems;
            }
            namespace flexiblesusy
            {
                typedef ::FlexibleSUSY_CMSSM_2_4_0::flexiblesusy::Spectrum_generator_settings Spectrum_generator_settings;
            }
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
