//
// Frontend header generated by BOSS for GAMBIT backend HepLike 1.1.
//

#include "gambit/Backends/backend_types/HepLike_1_1/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
   namespace Backends
   {
      namespace HepLike_1_1
      {
         typedef ::HepLike_1_1::HL_Data HL_Data;
         typedef ::HepLike_1_1::HL_Gaussian HL_Gaussian;
         typedef ::HepLike_1_1::HL_BifurGaussian HL_BifurGaussian;
         typedef ::HepLike_1_1::HL_ExpPoints HL_ExpPoints;
         typedef ::HepLike_1_1::HL_Limit HL_Limit;
         typedef ::HepLike_1_1::HL_ProfLikelihood HL_ProfLikelihood;
         typedef ::HepLike_1_1::HL_nDimBifurGaussian HL_nDimBifurGaussian;
         typedef ::HepLike_1_1::HL_nDimGaussian HL_nDimGaussian;
         typedef ::HepLike_1_1::HL_nDimLikelihood HL_nDimLikelihood;
      }
   }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
