//
// Frontend header generated by BOSS for GAMBIT backend vevacious 1.0.
//

#include "gambit/Backends/backend_types/vevacious_1_0/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace vevacious_1_0
        {
            namespace VevaciousPlusPlus
            {
                typedef ::vevacious_1_0::VevaciousPlusPlus::VevaciousPlusPlus VevaciousPlusPlus;
            }
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
