#!/bin/bash
#
#  GUM: GAMBIT Universal Model Machine
#  ***********************************
#  \file
#
#  Wrapper script to select the
#  correct python executable
#
#  *************************************
#
#  \author Tomas Gonzalo
#          (tomas.gonzalo@monash.edu)
#  \date 2020
#
#  *************************************


# Make sure the cmake_variables.py file exists,
# where we can find the location of python executable
cmake_variables_file="${PWD}/src/cmake_variables.py"
if [ -f ${cmake_variables_file} ]
then

  # Extract location of python executable
  python_exec=`awk -F\" '/^PYTHON_EXECUTABLE/{print $2}' ${cmake_variables_file}`

  # If the variable does not appear on the cmake_variable file, something went wrong
  if [ -z ${python_exec} ]
  then
    echo "ERROR"
    echo "  Could not find location of python executable in ${cmake_variables_file}."
    echo "  Please check that gum has finished compiling."
    exit 1
  fi

  # If the executable file does not exist, also throw error
  if [ ! -f ${python_exec} ]
  then
    echo "ERROR"
    echo "  Could not find python executable in ${python_exec}."
    echo "  Please make sure that it exists."
    exit 1
  fi

 # Everything seems fine, run gum
 ${python_exec} "${PWD}/gum.py" "$@"

else
  echo "ERROR"
  echo "  Required file cmake_variables.py not found."
  echo "  Please compile gum first."
  exit 1
fi
