//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Py8Collider typedefs for models in           
///  ColliderBit.                                 
///                                               
///  This file is automatically generated by      
///  collider_harvester.py.  Do not modify.       
///                                               
///  *********************************************
///                                               
///  \author The GAMBIT Collaboration            
///  \date 12:21PM on September 16, 2019
///                                               
///  *********************************************
                                                  
#pragma once                                      
                                                  
#include "gambit/ColliderBit/colliders/Pythia8/Py8Collider.hpp"
                                                  
namespace Gambit                                  
{                                                 
  namespace ColliderBit                           
  {                                               
                                                  
    /// Typedefs for each Pythia collider         
    /// @{                                        
    typedef Py8Collider<Pythia_default::Pythia8::Pythia, Pythia_default::Pythia8::Event> Py8Collider_defaultversion;
    typedef Py8Collider<Pythia_EM_default::Pythia8::Pythia, Pythia_EM_default::Pythia8::Event> Py8Collider_EM_defaultversion;
    /// @}

  }
}
