#ifndef __wrapper_CMSSM_spectrum_generator_Two_scale_FlexibleSUSY_CMSSM_2_4_0_h__
#define __wrapper_CMSSM_spectrum_generator_Two_scale_FlexibleSUSY_CMSSM_2_4_0_h__


#include "wrapper_CMSSM_spectrum_generator_Two_scale_decl.h"
#include "wrapper_CMSSM_spectrum_generator_Two_scale_def.h"


#endif /* __wrapper_CMSSM_spectrum_generator_Two_scale_FlexibleSUSY_CMSSM_2_4_0_h__ */
