//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Super Renormalizable Higgs Portal DM
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author Sebastian Hoof
///          (s.hoof15@imperial.ac.uk)
///  \date 2019 Feb
///
///  *********************************************

#include <cmath>

#include "gambit/Models/model_macros.hpp"
#include "gambit/Models/model_helpers.hpp"
#include "gambit/Logs/logger.hpp"
#include "gambit/Utils/numerical_constants.hpp"
#include "gambit/DarkBit/DarkBit_types.hpp"

#include "gambit/Models/models/SuperRenormHP.hpp"

#define MODEL SuperRenormHP
#define FRIEND ModifiedGravityYukawa
void MODEL_NAMESPACE::SuperRenormHP_to_ModifiedGravityYukawa (const ModelParameters &myparams, ModelParameters &friendparams)
{
    USE_MODEL_PIPE(FRIEND) // get pipe for "interpret as friend" function
    logger()<<"Running interpret_as_friend calculations for SuperRenormHP -> ModifiedGravityYukawa ..."<<EOM;

    const double mH = 125.1*1e9; // Higgs boson mass [eV] (PDG 2019)
    const double mT = 172.9*1e9; // top quark mass [eV] (PDG 2019)
    const double v = 246e9; // electroweak vev [eV]
    const double alphaS = pi; // strong coupling constant
    const double mS = myparams["mS"], theta = myparams["theta"];
    const double tau = 4*pow(mT/mH, 2.);
    const double g = alphaS/8./pi*tau*(1+(1-tau)*pow(asin(sqrt(1./tau)), 2.)); // effective Higgs-gluon coupling constant (generated by top quark loop)
    const double f = v/theta/g;
    const double Mp = Gambit::m_planck*1e9; // Planck mass [eV]
    const double hbar = Gambit::hbar*1e9;  // reduced Planck constant [eV.s]
    const double cs = Gambit::s2cm; // speed of light [cm/s]

    friendparams.setValue("alpha", 4*Gambit::pi*pow(Mp/f, 2));
    friendparams.setValue("lambda", hbar*cs/mS);
}

/* void MODEL_NAMESPACE::SuperRenormHP_to_ModifiedGravityYukawa (const ModelParameters &myparams, ModelParameters &friendparams) */
/* { */
/*     USE_MODEL_PIPE(FRIEND) // get pipe for "interpret as friend" function */
/*     logger()<<"Running interpret_as_friend calculations for SuperRenormHP -> ModifiedGravityYukawa ..."<<EOM; */

/*     const DarkBit::Higgs_Nucleon_coupling_fN couplings = *Dep::Higgs_Nucleon_coupling_fN; */
/*     const double fN = couplings.proton; */

/*     const double v = 246e9; // electroweak vev [eV] */
/*     const double mS = myparams["mS"], theta = myparams["theta"]; */
/*     const double f = v/theta/fN; */
/*     const double Mp = Gambit::m_planck*1e9; // Planck mass [eV] */
/*     const double hbar = Gambit::hbar*1e9;  // reduced Planck constant [eV.s] */
/*     const double cs = Gambit::s2cm; // speed of light [cm/s] */

/*     friendparams.setValue("alpha", 4*Gambit::pi*pow(Mp/f, 2)); */
/*     friendparams.setValue("lambda", hbar*cs/mS); */
/* } */
#undef FRIEND
#undef MODEL
