#ifndef __wrapper_Spectrum_generator_settings_FlexibleSUSY_CMSSM_2_0_1_h__
#define __wrapper_Spectrum_generator_settings_FlexibleSUSY_CMSSM_2_0_1_h__


#include "wrapper_Spectrum_generator_settings_decl.h"
#include "wrapper_Spectrum_generator_settings_def.h"


#endif /* __wrapper_Spectrum_generator_settings_FlexibleSUSY_CMSSM_2_0_1_h__ */
