#ifndef __wrapper_CMSSM_slha_Model_Two_scale_FlexibleSUSY_CMSSM_2_0_1_h__
#define __wrapper_CMSSM_slha_Model_Two_scale_FlexibleSUSY_CMSSM_2_0_1_h__


#include "wrapper_CMSSM_slha_Model_Two_scale_decl.h"
#include "wrapper_CMSSM_slha_Model_Two_scale_def.h"


#endif /* __wrapper_CMSSM_slha_Model_Two_scale_FlexibleSUSY_CMSSM_2_0_1_h__ */
