#ifndef __wrapper_CMSSM_spectrum_generator_interface_FlexibleSUSY_CMSSM_2_0_1_h__
#define __wrapper_CMSSM_spectrum_generator_interface_FlexibleSUSY_CMSSM_2_0_1_h__


#include "wrapper_CMSSM_spectrum_generator_interface_decl.h"
#include "wrapper_CMSSM_spectrum_generator_interface_def.h"


#endif /* __wrapper_CMSSM_spectrum_generator_interface_FlexibleSUSY_CMSSM_2_0_1_h__ */
