#ifndef __wrapper_CMSSM_mass_eigenstates_FlexibleSUSY_CMSSM_2_0_1_h__
#define __wrapper_CMSSM_mass_eigenstates_FlexibleSUSY_CMSSM_2_0_1_h__


#include "wrapper_CMSSM_mass_eigenstates_decl.h"
#include "wrapper_CMSSM_mass_eigenstates_def.h"


#endif /* __wrapper_CMSSM_mass_eigenstates_FlexibleSUSY_CMSSM_2_0_1_h__ */
