//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  ColliderBit sources for model MDMSM.
///
///  Automatically generated by GUM.
///
///  \author The GAMBIT Collaboration
///          http://gambit.hepforge.org
///  \date 04:53PM on March 08, 2021
///
///  *********************************************

#include "gambit/ColliderBit/getPy8Collider.hpp"
#include "gambit/ColliderBit/generateEventPy8Collider.hpp"


namespace Gambit
{
  namespace ColliderBit
  {

    // Get spectrum and decays for Pythia
    GET_SPECTRUM_AND_DECAYS_FOR_PYTHIA_NONSUSY(getSpectrumAndDecaysForPythia_MDMSM, MDMSM_spectrum)

    // Get Monte Carlo event generator
    GET_SPECIFIC_PYTHIA(getPythia_MDMSM, Pythia_MDMSM_default, _MDMSM)
    GET_PYTHIA_AS_BASE_COLLIDER(getPythia_MDMSMAsBase)

    // Run event generator
    GET_PYTHIA_EVENT(generateEventPythia_MDMSM)

  }
}
